nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true

unsafeHttpWhitelist:
  - 192.168.10.40

yarnPath: .yarn/releases/yarn-3.6.0.cjs

nmHoistingLimits: workspaces 
